Repository ludwig-ai/ludwig, pull requests merged in 2022-09, with the labels that each got.

#2447 [tests] Added more explicit lifecycle management to Ray clusters during tests
  .github/workflows/pytest.yml
  ludwig/backend/ray.py
  ludwig/hyperopt/execution.py
  ludwig/utils/automl/ray_utils.py
  tests/conftest.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_gbm.py
  tests/integration_tests/test_hyperopt_ray_horovod.py
  tests/integration_tests/test_missing_value_strategy.py
  tests/integration_tests/test_postprocessing.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_ray.py
  tests/integration_tests/test_trainer.py
  tests/integration_tests/utils.py
Labels: tests

#2480 fix: Automatically assign title to OneOfOptionsField
  ludwig/schema/utils.py
  tests/ludwig/marshmallow/test_fields_misc.py
Labels: bug

#2485 Fixed usage of checkpoints for AutoML in Ray 2.0
  ludwig/automl/automl.py
  ludwig/hyperopt/execution.py
  tests/integration_tests/test_automl.py
  tests/integration_tests/test_hyperopt.py
Labels: bug, v0.6

#2500 Added workflow to auto cherry-pick into release branches
  .github/workflows/cherry-pick-release.yml
Labels: release-0.6

#2501 Enable hyperopt to be launched from a ray client
  ludwig/hyperopt/execution.py
Labels: release-0.6

#2490 GBM: support hyperopt
  ludwig/models/base.py
  ludwig/models/ecd.py
  ludwig/models/gbm.py
  ludwig/schema/trainer.py
  ludwig/trainers/trainer.py
  ludwig/trainers/trainer_lightgbm.py
  ludwig/utils/trainer_utils.py
  tests/conftest.py
  tests/integration_tests/test_gbm.py
Labels: release-0.6

#2505 AUTO:
  ludwig/models/base.py
  ludwig/models/ecd.py
  ludwig/models/gbm.py
  ludwig/schema/trainer.py
  ludwig/trainers/trainer.py
  ludwig/trainers/trainer_lightgbm.py
  ludwig/utils/trainer_utils.py
  tests/conftest.py
  tests/integration_tests/test_gbm.py
Labels: autocreated

#2504 AUTO: Enable hyperopt to be launched from a ray client
  ludwig/hyperopt/execution.py
Labels: autocreated

#2508 Fixed support for distributed datasets in create_auto_config
  ludwig/automl/auto_tune_config.py
  ludwig/automl/automl.py
  ludwig/automl/base_config.py
  ludwig/utils/automl/data_source.py
  ludwig/utils/automl/type_inference.py
  ludwig/utils/misc_utils.py
  tests/integration_tests/test_automl.py
  tests/ludwig/utils/automl/test_type_inference.py
Labels: bug, release-0.6

#2513 AUTO:
  ludwig/automl/auto_tune_config.py
  ludwig/automl/automl.py
  ludwig/automl/base_config.py
  ludwig/utils/automl/data_source.py
  ludwig/utils/automl/type_inference.py
  ludwig/utils/misc_utils.py
  tests/integration_tests/test_automl.py
  tests/ludwig/utils/automl/test_type_inference.py
Labels: autocreated

#2515 Surfacing dataset statistics in hyperopt
  ludwig/api.py
  ludwig/datasets/loaders/__init__.py
  ludwig/hyperopt/run.py
  ludwig/utils/dataset_utils.py
Labels: release-0.6

#2517 GBM: correctly compute early stopping
  ludwig/trainers/trainer_lightgbm.py
Labels: release-0.6

#2521 AUTO:
  ludwig/trainers/trainer_lightgbm.py
Labels: autocreated

#2527 Fix get_best_model in hyperopt for Ray 1.12
  ludwig/hyperopt/execution.py
Labels: release-0.6

#2528 AUTO:
  ludwig/hyperopt/execution.py
Labels: autocreated

#2530 Update README to be consistent with ludwig.ai home page.
  README.md
  setup.py
Labels: release-0.6

#2533 Add missing declarative ML image in README
  images/why_declarative.png
Labels: release-0.6

#2534 AUTO:
  images/why_declarative.png
Labels: autocreated

#2523 Updated schedule logic for placement groups for ray backend
  ludwig/backend/ray.py
  tests/integration_tests/test_ray.py
Labels: release-0.6

#2535 Hyperopt: Log warning with num_extra_trials if all grid search parameters and num_samples > 1
  ludwig/constants.py
  ludwig/hyperopt/run.py
  tests/integration_tests/test_hyperopt.py
Labels: release-0.6

#2542 AUTO:
  ludwig/constants.py
  ludwig/hyperopt/run.py
  tests/integration_tests/test_hyperopt.py
Labels: autocreated

#2543 ZScore Normalization Failure When Using Constant Value Number Feature
  ludwig/features/number_feature.py
  tests/integration_tests/test_number_feature.py
Labels: bug, release-0.6

#2546 AUTO:
  ludwig/features/number_feature.py
  tests/integration_tests/test_number_feature.py
Labels: autocreated

#2551 Added tests for init_config and render_config CLI commands
  ludwig/automl/automl.py
  ludwig/automl/base_config.py
  ludwig/backend/base.py
  ludwig/backend/horovod.py
  ludwig/backend/ray.py
  ludwig/utils/system_utils.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_ray.py
Labels: release-0.6

#2552 AUTO:
  ludwig/automl/automl.py
  ludwig/automl/base_config.py
  ludwig/backend/base.py
  ludwig/backend/horovod.py
  ludwig/backend/ray.py
  ludwig/utils/system_utils.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_ray.py
Labels: autocreated

#2553 Ensure bfill/ffill leave no residual NaNs in the dataset during preprocessing
  ludwig/data/preprocessing.py
  tests/integration_tests/test_ray.py
  tests/integration_tests/utils.py
Labels: release-0.6

#2557 AUTO:
  ludwig/data/preprocessing.py
  tests/integration_tests/test_ray.py
  tests/integration_tests/utils.py
Labels: autocreated

#2570 Fixed typehint and removed unused utility function
  ludwig/automl/base_config.py
  ludwig/utils/automl/ray_utils.py
Labels: release-0.6

#2571 AUTO:
  ludwig/data/dataframe/dask.py
  ludwig/features/date_feature.py
  ludwig/models/predictor.py
  ludwig/utils/data_utils.py
  requirements_distributed.txt
  tests/integration_tests/test_ray.py
  tests/integration_tests/utils.py
Labels: autocreated

#2572 AUTO:
  ludwig/automl/base_config.py
  ludwig/utils/automl/ray_utils.py
Labels: autocreated
