Repository ludwig-ai/ludwig, pull requests merged in 2022-07, with the labels that each got.

#2247 Fixed handling of invalud number values to treat as missing values
  ludwig/data/preprocessing.py
  tests/integration_tests/test_preprocessing.py
Labels: bug

#2248 Fixed splitting when providing pre-split inputs
  ludwig/data/dataset/pandas.py
  ludwig/data/dataset/ray.py
  ludwig/data/preprocessing.py
  requirements.txt
  tests/integration_tests/test_preprocessing.py
Labels: bug, v0.6

#2286 Fixed default eval_batch_size when setting batch_size=auto
  ludwig/api.py
  ludwig/trainers/trainer.py
  tests/integration_tests/test_trainer.py
Labels: bug

#2304 Fix error in postproc_predictions calculation in model.evaluate()
  ludwig/api.py
  ludwig/data/utils.py
  ludwig/utils/dataframe_utils.py
Labels: bug

#2208 2130 rfc add configuration section for global feature parameters
  ludwig/api.py
  ludwig/constants.py
  ludwig/data/cache/util.py
  ludwig/data/preprocessing.py
  ludwig/features/feature_registries.py
  ludwig/hyperopt/run.py
  ludwig/schema/__init__.py
  ludwig/utils/backward_compatibility.py
  ludwig/utils/config_utils.py
  ludwig/utils/defaults.py
  tests/integration_tests/test_config_global_defaults.py
  tests/integration_tests/test_model_training_options.py
  tests/ludwig/utils/test_backward_compatibility.py
  tests/ludwig/utils/test_defaults.py
Labels: feature, v0.6
