Repository ludwig-ai/ludwig, pull requests merged in 2022-06, with the labels that each got.

#2107 First pass at trainer schema separation.
  ludwig/api.py
  ludwig/backend/base.py
  ludwig/backend/ray.py
  ludwig/schema/__init__.py
  ludwig/schema/trainer.py
  ludwig/schema/utils.py
  ludwig/trainers/base.py
  ludwig/trainers/trainer_lightgbm.py
  ludwig/utils/misc_utils.py
  tests/integration_tests/test_gbm.py
Labels: productivity and code quality

#2141 Fixes FILL_WITH_MEAN missing value strategy with appropriate cast
  ludwig/data/preprocessing.py
  tests/integration_tests/test_missing_value_strategy.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/utils.py
Labels: bug

#1949 Adds mechanism for calibrating probabilities for category and binary features
  ludwig/api.py
  ludwig/backend/ray.py
  ludwig/features/base_feature.py
  ludwig/features/binary_feature.py
  ludwig/features/category_feature.py
  ludwig/models/calibrator.py
  ludwig/models/predictor.py
  ludwig/models/trainer.py
  ludwig/utils/calibration.py
  tests/integration_tests/test_ray.py
  tests/ludwig/utils/test_calibration.py
Labels: feature, v0.6

#2132 Restructured split config and added datetime splitting
  examples/insurance_lite/config.yaml
  ludwig/data/concatenate_datasets.py
  ludwig/data/dataframe/base.py
  ludwig/data/dataframe/dask.py
  ludwig/data/dataframe/modin.py
  ludwig/data/dataframe/pandas.py
  ludwig/data/preprocessing.py
  ludwig/data/split.py
  ludwig/features/date_feature.py
  ludwig/hyperopt/run.py
  ludwig/utils/backward_compatibility.py
  ludwig/utils/data_utils.py
  ludwig/utils/defaults.py
  ludwig/utils/math_utils.py
  ludwig/utils/registry.py
  ludwig/visualize.py
  tests/integration_tests/test_model_save_and_load.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_visualization.py
  tests/integration_tests/test_visualization_api.py
  tests/integration_tests/utils.py
  tests/ludwig/data/test_split.py
  tests/ludwig/utils/test_defaults.py
Labels: feature, v0.6

#2027 feat: Added model type GBM (LightGBM tree learner), as an alternative to ECD
  .github/workflows/pytest.yml
  examples/lightgbm/config.yaml
  examples/lightgbm/config_higgs.yaml
  examples/lightgbm/train.py
  ludwig/api.py
  ludwig/backend/base.py
  ludwig/backend/horovod.py
  ludwig/backend/ray.py
  ludwig/constants.py
  ludwig/data/dataset/pandas.py
  ludwig/data/postprocessing.py
  ludwig/data/utils.py
  ludwig/decoders/generic_decoders.py
  ludwig/encoders/generic_encoders.py
  ludwig/features/base_feature.py
  ludwig/models/base.py
  ludwig/models/ecd.py
  ludwig/models/gbm.py
  ludwig/models/inference.py
  ludwig/models/predictor.py
  ludwig/models/registry.py
  ludwig/schema/__init__.py
  ludwig/schema/trainer.py
  ludwig/schema/utils.py
  ludwig/trainers/__init__.py
  ludwig/trainers/base.py
  ludwig/trainers/registry.py
  ludwig/trainers/trainer.py
  ludwig/trainers/trainer_lightgbm.py
  ludwig/utils/defaults.py
  requirements_tree.txt
  setup.py
  tests/integration_tests/test_gbm.py
  tests/integration_tests/test_input_feature_tied.py
  tests/integration_tests/test_model_save_and_load.py
  tests/integration_tests/test_torchscript.py
  tests/integration_tests/utils.py
  tests/ludwig/features/test_category_feature.py
  tests/ludwig/features/test_image_feature.py
  tests/ludwig/features/test_number_feature.py
  tests/ludwig/features/test_set_feature.py
  tests/ludwig/marshmallow/test_marshmallow_misc.py
  tests/ludwig/utils/test_defaults.py
  tests/ludwig/utils/test_validate_config_trainer.py
Labels: feature, v0.6

#2133 feat: Adding feature type shared parameter capability for hyperopt
  ludwig/constants.py
  ludwig/features/sequence_feature.py
  ludwig/hyperopt/execution.py
  ludwig/hyperopt/run.py
  ludwig/utils/config_utils.py
  tests/integration_tests/test_hyperopt.py
Labels: feature, v0.6
