Repository ludwig-ai/ludwig, pull requests merged in 2022-10, with the labels that each got.

#2577 Use Ray Air Checkpoint to sync files between trial workers
  ludwig/hyperopt/execution.py
  ludwig/trainers/trainer.py
  requirements_distributed.txt
  requirements_hyperopt.txt
  tests/integration_tests/test_hyperopt_ray.py
Labels: release-0.6

#2581 AUTO:
  ludwig/hyperopt/execution.py
  ludwig/trainers/trainer.py
  requirements_distributed.txt
  requirements_hyperopt.txt
  tests/integration_tests/test_hyperopt_ray.py
Labels: autocreated

#2574 GBM bugfix: matching predictions LightGBM, hummingbird
  ludwig/models/gbm.py
  ludwig/trainers/trainer_lightgbm.py
  tests/integration_tests/test_gbm.py
  tests/integration_tests/test_model_save_and_load.py
Labels: release-0.6

#2583 AUTO:
  ludwig/models/gbm.py
  ludwig/trainers/trainer_lightgbm.py
  tests/integration_tests/test_gbm.py
  tests/integration_tests/test_model_save_and_load.py
Labels: autocreated

#2566 specify seed in RayDataset shuffling
  ludwig/data/dataset/ray.py
  tests/ludwig/models/test_training_determinism.py
Labels: release-0.6

#2590 AUTO:
  ludwig/data/dataset/ray.py
  tests/ludwig/models/test_training_determinism.py
Labels: autocreated

#2584 update docker with torch wheel
  docker/ludwig-ray/Dockerfile
Labels: release-0.6

#2591 AUTO:
  docker/ludwig-ray/Dockerfile
Labels: autocreated

#2593 Remove duplicate option
  ludwig/schema/encoders/sequence_encoders.py
Labels: release-0.6

#2594 AUTO:
  ludwig/schema/encoders/sequence_encoders.py
Labels: autocreated

#2598 Fixed issue when uploading output directory artifacts to remote filesystems
  .github/workflows/pytest.yml
  ludwig/api.py
  ludwig/utils/fs_utils.py
  ludwig/utils/misc_utils.py
  tests/integration_tests/test_remote.py
  tests/integration_tests/utils.py
Labels: bug, release-0.6

#2605 Allow explicitly plumbing through nics
  .github/workflows/pytest.yml
  ludwig/backend/ray.py
  tests/conftest.py
  tests/ludwig/backend/test_ray.py
Labels: release-0.6

#2600 bug: fix relative import in optimizers.py
  ludwig/schema/optimizers.py
Labels: release-0.6

#2609 AUTO:
  ludwig/schema/optimizers.py
Labels: autocreated

#2608 AUTO:
  .github/workflows/pytest.yml
  ludwig/backend/ray.py
  tests/conftest.py
  tests/ludwig/backend/test_ray.py
Labels: autocreated

#2613 AUTO:
  ludwig/schema/trainer.py
Labels: autocreated

#2615 Add splitter that deterministically splits on an ID column
  ludwig/data/split.py
  ludwig/schema/split.py
  tests/ludwig/data/test_split.py
Labels: feature

#2616 fix(explain): missing columns for fixed split
  ludwig/explain/util.py
  tests/integration_tests/test_explain.py
Labels: release-0.6

#2618 AUTO:
  ludwig/explain/util.py
  tests/integration_tests/test_explain.py
Labels: autocreated

#2579 feat: adds `max_batch_size` to auto batch size functionality
  ludwig/constants.py
  ludwig/schema/metadata/trainer_metadata.py
  ludwig/schema/trainer.py
  ludwig/trainers/trainer.py
  ludwig/utils/backward_compatibility.py
  tests/ludwig/utils/test_backward_compatibility.py
  tests/ludwig/utils/test_defaults.py
Labels: release-0.6

#2631 Remove hyperopt from config when running train through cli
  ludwig/train.py
Labels: release-0.6

#2634 AUTO:
  ludwig/train.py
Labels: autocreated

#2524 Ensure resource availability for ray datasets workloads when running on cpu clusters
  ludwig/backend/base.py
  ludwig/backend/horovod.py
  ludwig/backend/ray.py
  ludwig/constants.py
  ludwig/hyperopt/run.py
  ludwig/hyperopt/utils.py
  tests/integration_tests/test_hyperopt.py
  tests/integration_tests/test_hyperopt_ray.py
  tests/integration_tests/test_hyperopt_ray_horovod.py
  tests/ludwig/backend/test_ray.py
Labels: release-0.6

#2636 AUTO:
  ludwig/backend/base.py
  ludwig/backend/horovod.py
  ludwig/backend/ray.py
  ludwig/constants.py
  ludwig/hyperopt/run.py
  ludwig/hyperopt/utils.py
  tests/integration_tests/test_hyperopt.py
  tests/integration_tests/test_hyperopt_ray.py
  tests/integration_tests/test_hyperopt_ray_horovod.py
  tests/ludwig/backend/test_ray.py
Labels: autocreated

#2614 Unpin Ray nightly in CI
  .github/workflows/pytest.yml
  ludwig/__init__.py
  ludwig/utils/visualization_utils.py
Labels: release-0.6

#2646 AUTO:
  .github/workflows/pytest.yml
  ludwig/__init__.py
  ludwig/utils/visualization_utils.py
Labels: autocreated

#2650 Fixed automl APIs to work with remote filesystems
  ludwig/automl/automl.py
  ludwig/models/ecd.py
  tests/integration_tests/test_automl.py
Labels: release-0.6

#2653 Fixed race condition in schema validation
  ludwig/schema/__init__.py
Labels: release-0.6

#2658 Fixed --gpu_memory_limit in CLI to interpret as fraction of GPU memory
  ludwig/api.py
  ludwig/collect.py
  ludwig/evaluate.py
  ludwig/experiment.py
  ludwig/hyperopt/run.py
  ludwig/hyperopt_cli.py
  ludwig/predict.py
  ludwig/preprocess.py
  ludwig/train.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_horovod.py
Labels: bug, release-0.6

#2660 AUTO:
  ludwig/api.py
  ludwig/collect.py
  ludwig/evaluate.py
  ludwig/experiment.py
  ludwig/hyperopt/run.py
  ludwig/hyperopt_cli.py
  ludwig/predict.py
  ludwig/preprocess.py
  ludwig/train.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_horovod.py
Labels: autocreated

#2659 Set internal only flags
  ludwig/schema/combiners/utils.py
  ludwig/schema/defaults/defaults.py
  ludwig/schema/encoders/sequence_encoders.py
  ludwig/schema/encoders/text_encoders.py
  ludwig/schema/features/preprocessing/utils.py
  ludwig/schema/features/utils.py
  ludwig/schema/metadata/combiner_metadata.py
  ludwig/schema/metadata/encoder_metadata.py
  ludwig/schema/preprocessing.py
  ludwig/schema/trainer.py
Labels: release-0.6

#2673 Unpin protobuf
  requirements.txt
Labels: release-0.6

#2677 AUTO:
  requirements.txt
Labels: autocreated

#2640 Allow Ray Tune callbacks to be passed into hyperopt and log model config
  ludwig/hyperopt/execution.py
  ludwig/hyperopt/run.py
  tests/integration_tests/test_hyperopt_ray.py
Labels: release-0.6

#2685 Use fully rendered config dictionary when accessing model.config
  examples/lbfgs/model.py
  ludwig/api.py
  ludwig/explain/explainer.py
  ludwig/explain/util.py
  ludwig/hyperopt/execution.py
  ludwig/serve.py
  ludwig/utils/neuropod_utils.py
  ludwig/utils/triton_utils.py
  tests/integration_tests/test_experiment.py
  tests/integration_tests/test_mlflow.py
  tests/integration_tests/test_triton.py
  tests/ludwig/automl/__init__.py
  tests/ludwig/automl/test_utils.py
  tests/regression_tests/model/test_old_models.py
Labels: bug

#2692 Fix validator for reduce_learning_rate_on_plateau
  ludwig/schema/trainer.py
Labels: release-0.6

#2695 Fix InputDataError to be serializeable
  ludwig/error.py
  tests/ludwig/utils/test_errors.py
Labels: bug

#2702 Fixed bug with non-category outputs in RayIntegratedGradientsExplainer
  ludwig/explain/captum_ray.py
  tests/integration_tests/test_explain.py
Labels: bug

#2717 Fixed Horovod to be an optional import when doing Hyperopt
  ludwig/backend/ray.py
Labels: release-0.6

#2719 AUTO:
  ludwig/backend/ray.py
Labels: autocreated
