Repository ludwig-ai/ludwig, pull requests merged in 2023-03, with the labels that each got.

#3167 Unpin pyarrow
  requirements_distributed.txt
Labels: release-0.7

#3166 Make Horovod an optional dependency when using Ray
  ludwig/backend/_ray210_compat.py
  ludwig/backend/ray.py
  ludwig/distributed/__init__.py
  ludwig/distributed/_ray_210_compat.py
  ludwig/distributed/base.py
  ludwig/distributed/ddp.py
  ludwig/distributed/horovod.py
  tests/ludwig/backend/test_ray.py
Labels: release-0.7

#3171 AUTO:
  requirements_distributed.txt
Labels: autocreated

#3172 AUTO:
  ludwig/backend/_ray210_compat.py
  ludwig/backend/ray.py
  ludwig/distributed/__init__.py
  ludwig/distributed/_ray_210_compat.py
  ludwig/distributed/base.py
  ludwig/distributed/ddp.py
  ludwig/distributed/horovod.py
  tests/ludwig/backend/test_ray.py
Labels: autocreated

#3173 Fix TorchVision channel preprocessing
  ludwig/features/image_feature.py
  ludwig/utils/image_utils.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_torchscript.py
  tests/ludwig/utils/test_image_utils.py
Labels: bug, release-0.7

#3178 Fix TorchVision channel preprocessing (#3173)
  ludwig/features/image_feature.py
  ludwig/utils/image_utils.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_torchscript.py
  tests/ludwig/utils/test_image_utils.py
Labels: autocreated

#3179 Bump Ludwig to v0.7.1
  ludwig/globals.py
  setup.py
Labels: release-0.7

#3180 Bump Ludwig to v0.7.1 (#3179)
  ludwig/globals.py
  setup.py
Labels: autocreated

#3184 Remove hard dependency on ludwig[tree]. Check `model.type()` instead of `instanceof(model)`.
  ludwig/models/predictor.py
Labels: bug, release-0.7

#3194 AUTO:
  ludwig/models/predictor.py
Labels: autocreated

#3191 Guarantee determinism when sampling (either overall via `sample_ratio`, or while balancing data)
  ludwig/data/preprocessing.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_ray.py
  tests/ludwig/utils/test_class_balancing.py
Labels: bug, release-0.7

#3199 AUTO:
  ludwig/data/preprocessing.py
  tests/integration_tests/test_preprocessing.py
  tests/integration_tests/test_ray.py
  tests/ludwig/utils/test_class_balancing.py
Labels: autocreated

#3195 Fixes dict_hash discrepancy
  ludwig/data/cache/util.py
  ludwig/utils/data_utils.py
  tests/ludwig/data/test_cache_util.py
Labels: bug, release-0.7

#3204 AUTO:
  ludwig/data/cache/util.py
  ludwig/utils/data_utils.py
  tests/ludwig/data/test_cache_util.py
Labels: autocreated

#3186 Fix Docker image dependencies and add tests for minimal install
  .github/workflows/docker.yml
  .github/workflows/pytest.yml
  docker/ludwig-gpu/Dockerfile
  examples/getting_started/rotten_tomatoes.yaml
  examples/getting_started/run.sh
  ludwig/callbacks.py
  ludwig/check.py
  ludwig/cli.py
  ludwig/contrib.py
  ludwig/contribs/__init__.py
  ludwig/contribs/aim.py
  ludwig/contribs/comet.py
  ludwig/contribs/wandb.py
  ludwig/features/set_feature.py
  tests/integration_tests/test_hyperopt_ray.py
  tests/integration_tests/test_mlflow.py
  tests/ludwig/contrib/test_contrib.py
Labels: bug, release-0.7

#3206 AUTO:
  .github/workflows/pytest.yml
  ludwig/automl/defaults/combiner/tabnet_config.yaml
  ludwig/benchmarking/examples/process_config.py
  tests/integration_tests/test_automl.py
Labels: autocreated

#3207 AUTO:
  .github/workflows/docker.yml
  .github/workflows/pytest.yml
  docker/ludwig-gpu/Dockerfile
  examples/getting_started/rotten_tomatoes.yaml
  examples/getting_started/run.sh
  ludwig/callbacks.py
  ludwig/check.py
  ludwig/cli.py
  ludwig/contrib.py
  ludwig/contribs/__init__.py
  ludwig/contribs/aim.py
  ludwig/contribs/comet.py
  ludwig/contribs/wandb.py
  ludwig/features/set_feature.py
  tests/integration_tests/test_hyperopt_ray.py
  tests/integration_tests/test_mlflow.py
  tests/ludwig/contrib/test_contrib.py
Labels: autocreated

#3208 Bump to v0.7.2
  ludwig/globals.py
  setup.py
Labels: release-0.7

#3209 AUTO:
  ludwig/globals.py
  setup.py
Labels: autocreated

#3232 Remove partial RayTune checkpoints for trials that have not completed because of forceful termination
  ludwig/hyperopt/execution.py
  tests/integration_tests/test_hyperopt.py
Labels: bug, release-0.7

#3237 AUTO:
  ludwig/hyperopt/execution.py
  tests/integration_tests/test_hyperopt.py
Labels: autocreated

#3238 Replace NaN in timeseries rows with `padding_value`
  ludwig/features/timeseries_feature.py
  ludwig/schema/features/preprocessing/timeseries.py
  tests/integration_tests/test_timeseries_feature.py
Labels: release-0.7

#3240 AUTO:
  ludwig/features/timeseries_feature.py
  ludwig/schema/features/preprocessing/timeseries.py
  tests/integration_tests/test_timeseries_feature.py
Labels: autocreated

#3241 Persist Dask Dataframe after binary image/audio reads
  ludwig/backend/ray.py
Labels: bug, release-0.7

#3243 AUTO:
  ludwig/backend/ray.py
Labels: autocreated

#3251 Filter entities from comparator combiner when not listed in input_features
  ludwig/schema/combiners/comparator.py
  ludwig/schema/model_types/base.py
  ludwig/schema/model_types/utils.py
  tests/ludwig/config_validation/test_checks.py
Labels: release-0.7

#3234 Fixes torch DDP distributed metric computation for AUROC
  ludwig/features/base_feature.py
  ludwig/modules/metric_modules.py
  ludwig/utils/horovod_utils.py
  tests/integration_tests/test_ray.py
Labels: release-0.7

#3226 feat: Add env var `LUDWIG_SCHEMA_VALIDATION_POLICY` to change marshmallow validation strictness
  ludwig/constants.py
  ludwig/schema/features/preprocessing/utils.py
  ludwig/schema/utils.py
Labels: release-0.7

#3262 AUTO:
  ludwig/constants.py
  ludwig/schema/features/preprocessing/utils.py
  ludwig/schema/utils.py
Labels: autocreated

#3246 Add support for `model.compile` in PyTorch 2.0
  .github/workflows/pytest.yml
  ludwig/combiners/combiners.py
  ludwig/explain/captum.py
  ludwig/features/feature_registries.py
  ludwig/features/feature_utils.py
  ludwig/models/base.py
  ludwig/models/ecd.py
  ludwig/models/embedder.py
  ludwig/models/gbm.py
  ludwig/schema/metadata/configs/trainer.yaml
  ludwig/schema/trainer.py
  ludwig/serve.py
  ludwig/trainers/trainer.py
  ludwig/utils/trainer_utils.py
  tests/integration_tests/test_model_save_and_load.py
  tests/integration_tests/test_sequence_features.py
  tests/integration_tests/test_trainer.py
  tests/ludwig/encoders/test_text_encoders.py
  tests/ludwig/explain/test_util.py
  tests/ludwig/features/test_feature_utils.py
  tests/ludwig/models/test_trainable_image_layers.py
  tests/ludwig/utils/test_trainer_utils.py
Labels: release-0.7

#3264 Fix ludwig docker
  docker/ludwig/Dockerfile
Labels: release-0.7

#3265 AUTO:
  docker/ludwig/Dockerfile
Labels: autocreated

#3268 AUTO:
  ludwig/globals.py
  setup.py
Labels: autocreated

#3269 Fixed non-scalar (text, vector, set) output feature explanations
  ludwig/explain/captum.py
  tests/integration_tests/test_explain.py
Labels: bug

#3274 Fixed handling of datetime types in input parquet files
  ludwig/automl/base_config.py
  ludwig/data/split.py
  ludwig/utils/automl/type_inference.py
  ludwig/utils/strings_utils.py
  tests/ludwig/automl/test_base_config.py
  tests/ludwig/data/test_split.py
Labels: bug

#3276 Fix date explanations
  ludwig/explain/captum.py
  ludwig/features/date_feature.py
  tests/integration_tests/test_explain.py
Labels: bug

#3310 Fixed URI loading
  ludwig/api.py
  ludwig/utils/data_utils.py
  tests/ludwig/datasets/test_datasets.py
Labels: bug, release-0.7

#3308 Fixed cache_encoder_embeddings with tied weights
  ludwig/backend/base.py
  ludwig/backend/ray.py
  ludwig/data/preprocessing.py
  ludwig/features/base_feature.py
  tests/integration_tests/test_cached_preprocessing.py
Labels: bug
