Repository ludwig-ai/ludwig, pull requests merged in 2023-01, with the labels that each got.

#2965 fix: Fix `epochs` suggested range
  ludwig/schema/metadata/configs/trainer.yaml
  ludwig/schema/trainer.py
Labels: documentation

#2992 fix: Fix validation and serialization for `Boolean` and `OneOfOptionsField` fields
  ludwig/schema/utils.py
Labels: bug

#3001 Added ghost batch norm option for concat combiner
  ludwig/modules/fully_connected_modules.py
  ludwig/modules/normalization_modules.py
  ludwig/schema/combiners/concat.py
  tests/ludwig/combiners/test_combiners.py
Labels: feature
